version: "3.8"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    network_mode: "host"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./model/model_data:/var/lib/postgresql/data
