import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { post_api_url } from '../settings';
import PostListItem from '../components/PostListItem';
import useSWR from 'swr';
import Link from 'next/link';

const fetcher = async (url) => {
  const res = await fetch(url);

  // If the status code is not in the range 200-299,
  // we still try to parse and throw it.
  if (!res.ok) {
    const error = new Error("An error occurred while fetching the data.");
    // Attach extra info to the error object.
    error.info = await res.json();
    error.status = res.status;
    throw error;
  }
  const data = await res.json();
  console.log(res)
  console.log(data)

  return data;
};

export default function Home() {
  const { data, error } = useSWR(post_api_url, fetcher)
  const posts = data;
  // console.log([error, 1])
  // console.log([posts, data])
  if (error) return <div>{error}</div>;
  if (!posts) return <p>Loading...</p>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Next View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((currentPostData, currentPostIdx) => (
          <PostListItem postData={currentPostData} key={currentPostIdx} />
        ))}
        <Link href='post/new'>
          <button id="add_post_button">Add new post</button>
        </Link>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
